# Generated by Django 3.1 on 2020-08-07 05:54

from django.db import migrations, models
import django.db.models.deletion
import goodapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 370x334')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goodapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Старая цена')),
                ('article', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Артикул')),
                ('dimensions', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Габариты')),
                ('razmer_kpb', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Размер')),
                ('razmer_navolocek', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Размер наволочек')),
                ('tip_prostyni', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Тип простыни')),
                ('upakovka', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Упаковка')),
                ('fabric', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Состав')),
                ('duvet_cover_size', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Размер пододеяленика')),
                ('kind_id', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Код производителя')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Остаток')),
                ('weight', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Вес')),
                ('good_uid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goodapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(default=None, upload_to=goodapp.models.get_image_name, verbose_name='Изображение 550x685')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodapp.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goodapp.manufacturer', verbose_name='Производитель'),
        ),
    ]
