# Generated by Django 3.1 on 2020-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
    ]
