# Generated by Django 3.1 on 2020-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0002_picture_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='goodapp.Category', verbose_name='Категория'),
        ),
    ]
