# Generated by Django 3.1 on 2020-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0003_auto_20200826_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='goodapp.Category', verbose_name='Категория'),
        ),
    ]
