# Generated by Django 3.1 on 2020-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0005_auto_20200826_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='razmer_prostyni',
            field=models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='Тип простыни'),
        ),
    ]
