# Generated by Django 3.1 on 2020-08-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0006_good_razmer_prostyni'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='parent_good',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='goodapp.good', verbose_name='Родительский товар'),
        ),
    ]
