# Generated by Django 3.1 on 2020-09-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0008_good_is_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='parent_good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goodapp.good', verbose_name='Родительский товар'),
        ),
    ]
