# Generated by Django 3.1 on 2020-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0009_auto_20200917_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(to='goodapp.Category', verbose_name='Категории'),
        ),
    ]
